# Generated by Django 5.0.7 on 2024-08-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_company_mainproduct_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default=0, max_length=500, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
