# Generated by Django 5.0.7 on 2024-08-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='categoryy', to='main.subcategory'),
            preserve_default=False,
        ),
    ]
