# Generated by Django 4.2.7 on 2024-08-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_customuser_image_alter_customuser_purchases_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainproduct",
            name="ids",
            field=models.IntegerField(
                blank=True, default=0, unique=True, verbose_name="ids"
            ),
            preserve_default=False,
        ),
    ]
