# Generated by Django 4.2.7 on 2024-08-18 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_mainproduct_ids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainproduct",
            name="ids",
        ),
    ]
